In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 열 값이 다른지 확인하기

In [ ]:
import pandas as pd

# 첫 번째 데이터 셋의 열을 기준으로 설정합니다.

base_df = pd.read_csv('/content/drive/MyDrive/23년도 2학기 학술제/11-29/TripA01.csv',encoding='CP949', delimiter=';')
base_columns = base_df.columns



# 모든 데이터 셋이 같은 열을 가지는지 확인합니다.
for i in range(1, 33):
    file_name = f'/content/drive/MyDrive/23년도 2학기 학술제/11-29/TripA{i:02}.csv'
    df = pd.read_csv(file_name, encoding='CP949', delimiter=';')
    if not df.columns.equals(base_columns):
        print(f'TripA{i:02} has different columns')

print("All datasets have been checked.")

TripA03 has different columns
TripA04 has different columns
TripA05 has different columns
TripA06 has different columns
TripA07 has different columns
TripA08 has different columns
TripA09 has different columns
TripA10 has different columns
TripA11 has different columns
TripA12 has different columns
TripA13 has different columns
TripA14 has different columns
TripA15 has different columns
TripA16 has different columns
TripA17 has different columns
TripA18 has different columns
TripA19 has different columns
TripA20 has different columns
TripA21 has different columns
TripA22 has different columns
All datasets have been checked.

## 결측치가 존재하는지 확인

In [ ]:
import pandas as pd

# 결측치가 있는 파일 목록을 저장할 리스트
files_with_missing_values = []

# 파일명이 'TripA01.csv'부터 'TripA32.csv'까지 반복
for i in range(1, 39):
    # 파일명 생성
    file_name = f'/content/drive/MyDrive/23년도 2학기 학술제/11-29_변수처리/TripB{i:02}.csv'

    # pandas를 이용해 csv 파일 읽기
    df = pd.read_csv(file_name, encoding='CP949', delimiter=';')

    # DataFrame의 결측치 확인
    if df.isnull().values.any():
        # 결측치가 있다면 파일명을 리스트에 추가
        files_with_missing_values.append(file_name)

# 결측치가 있는 파일 목록 출력
for file_name in files_with_missing_values:
    print(file_name)

In [ ]:
import pandas as pd

# 결측치가 있는 파일 목록을 저장할 리스트
files_with_missing_values = []

# 파일명이 'TripA01.csv'부터 'TripA32.csv'까지 반복
for i in range(1, 39):
    # 파일명 생성
    file_name = f'/content/drive/MyDrive/MeasurementData/TripB{i:02}.csv'

    # pandas를 이용해 csv 파일 읽기
    df = pd.read_csv(file_name, encoding='CP949', delimiter=';')

    # DataFrame의 결측치 확인
    if df.isnull().values.any():
        # 결측치가 있다면 파일명을 리스트에 추가
        files_with_missing_values.append(file_name)

# 결측치가 있는 파일 목록 출력
for file_name in files_with_missing_values:
    print(file_name)

/content/drive/MyDrive/MeasurementData/TripB04.csv
/content/drive/MyDrive/MeasurementData/TripB05.csv
/content/drive/MyDrive/MeasurementData/TripB06.csv
/content/drive/MyDrive/MeasurementData/TripB07.csv
/content/drive/MyDrive/MeasurementData/TripB08.csv
/content/drive/MyDrive/MeasurementData/TripB09.csv
/content/drive/MyDrive/MeasurementData/TripB10.csv
/content/drive/MyDrive/MeasurementData/TripB11.csv
/content/drive/MyDrive/MeasurementData/TripB12.csv
/content/drive/MyDrive/MeasurementData/TripB13.csv
/content/drive/MyDrive/MeasurementData/TripB14.csv
/content/drive/MyDrive/MeasurementData/TripB18.csv
/content/drive/MyDrive/MeasurementData/TripB19.csv
/content/drive/MyDrive/MeasurementData/TripB20.csv
/content/drive/MyDrive/MeasurementData/TripB21.csv
/content/drive/MyDrive/MeasurementData/TripB22.csv
/content/drive/MyDrive/MeasurementData/TripB23.csv
/content/drive/MyDrive/MeasurementData/TripB24.csv
/content/drive/MyDrive/MeasurementData/TripB25.csv
/content/drive/MyDrive/MeasurementData/TripB26.csv
/content/drive/MyDrive/MeasurementData/TripB28.csv
/content/drive/MyDrive/MeasurementData/TripB29.csv
/content/drive/MyDrive/MeasurementData/TripB30.csv
/content/drive/MyDrive/MeasurementData/TripB31.csv
/content/drive/MyDrive/MeasurementData/TripB32.csv
/content/drive/MyDrive/MeasurementData/TripB34.csv
/content/drive/MyDrive/MeasurementData/TripB35.csv
/content/drive/MyDrive/MeasurementData/TripB36.csv
/content/drive/MyDrive/MeasurementData/TripB37.csv
/content/drive/MyDrive/MeasurementData/TripB38.csv

In [ ]:
import pandas as pd

over = pd.read_excel('/content/drive/MyDrive/23년도 2학기 학술제/Overview.xlsx')

In [ ]:
over.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Trip                              70 non-null     object
 1   Date                              70 non-null     object
 2   Route/Area                        70 non-null     object
 3   Weather                           70 non-null     object
 4   Battery Temperature (Start) [°C]  70 non-null     int64
 5   Battery Temperature (End)         70 non-null     int64
 6   Battery State of Charge (Start)   70 non-null     float64
 7   Battery State of Charge (End)     70 non-null     float64
 8   Using Battery State of Charge     70 non-null     float64
 9   Ambient Temperature (Start) [°C]  70 non-null     float64
 10  Target Cabin Temperature          70 non-null     float64
 11  Distance [km]                     70 non-null     float64
 12  Duration [min]                    70 non-null     float64
 13  Fan                               70 non-null     object
 14  Note                              26 non-null     object
dtypes: float64(7), int64(2), object(6)
memory usage: 8.3+ KB

In [ ]:
over.columns

Index(['Trip', 'Date', 'Route/Area', 'Weather',
       'Battery Temperature (Start) [°C]', 'Battery Temperature (End)',
       'Battery State of Charge (Start)', 'Battery State of Charge (End)',
       'Using Battery State of Charge', 'Ambient Temperature (Start) [°C]',
       'Target Cabin Temperature', 'Distance [km]', 'Duration [min]', 'Fan',
       'Note'],
      dtype='object')

In [ ]:
over['Weather'].unique()

array(['sunny', 'slightly cloudy', 'rainy', 'cloudy',
       'dark, little rainy', 'dark', 'sunrise', 'sunset'], dtype=object)

In [ ]:
over['Route/Area'].unique()

array(['Munich East', 'Munich North', 'FTMRoute (2x)', 'FTMRoute',
       'Munich North + Fast Charging', 'Munich Northeast', 'Munich South',
       'Highway', 'FTMRoute reverse'], dtype=object)

In [ ]:
import pandas as pd

dfA = pd.read_csv('/content/drive/MyDrive/23년도 2학기 학술제/TripA01.csv',encoding='CP949', delimiter=';')

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# 시작 시간을 datetime 형식으로 변환합니다.
start_time_str = '2019-06-25_13-21-14'
start_time = datetime.strptime(start_time_str, '%Y-%m-%d_%H-%M-%S')

# time 열의 값을 읽어옵니다.
time_values = dfA['Time [s]']

# 각 time 값에 대해 시작 시간에 더하고, 이를 다시 문자열 형식으로 변환합니다.
new_time_values = [(start_time + timedelta(seconds=time)).strftime('%Y-%m-%d_%H-%M-%S') for time in time_values]

# 새로운 time 값을 데이터프레임에 적용합니다.
dfA['Time [s]'] = new_time_values

In [ ]:
import pandas as pd
import datetime

# 시간 데이터를 datetime 객체로 변환합니다.
dfA['Time [s]'] = pd.to_datetime(dfA['Time [s]'], format='%Y-%m-%d_%H-%M-%S')

# 0.1초 단위로 시간을 증가시킵니다.
new_time_list = []
for i in range(len(dfA)):
    new_time_list.append(dfA['Time [s]'][i])
    if (i+1) % 10 == 0:  # 10번째 인덱스마다
        new_time_list[-10:] = [new_time_list[-10] + datetime.timedelta(seconds=0.1*j) for j in range(10)]

# 데이터프레임의 마지막 행이 포함된 그룹이 10개보다 작은 경우를 처리합니다.
remainder = len(dfA) % 10
if remainder != 0:
    new_time_list[-remainder:] = [new_time_list[-remainder] + datetime.timedelta(seconds=0.1*j) for j in range(remainder)]

dfA['Time [s]'] = new_time_list

In [ ]:
dfA.head(20)

,Time [s],Velocity [km/h],Elevation [m],Throttle [%],Motor Torque [Nm],Longitudinal Acceleration [m/s^2],Regenerative Braking Signal,Battery Voltage [V],Battery Current [A],Battery Temperature [캜],...,AirCon Power [kW],Heater Signal,Heater Voltage [V],Heater Current [A],Ambient Temperature [캜],Coolant Temperature Heatercore [캜],Requested Coolant Temperature [캜],Coolant Temperature Inlet [캜],Heat Exchanger Temperature [캜],Cabin Temperature Sensor [캜]
0,2019-06-25 13:21:14.000,0.0,574.0,0.0,0.00,-0.03,0.0,391.40,-2.20,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
1,2019-06-25 13:21:14.100,0.0,574.0,0.0,0.00,0.00,0.0,391.40,-2.21,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
2,2019-06-25 13:21:14.200,0.0,574.0,0.0,0.00,-0.01,0.0,391.40,-2.26,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
3,2019-06-25 13:21:14.300,0.0,574.0,0.0,0.00,-0.03,0.0,391.40,-2.30,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
4,2019-06-25 13:21:14.400,0.0,574.0,0.0,0.00,-0.03,0.0,391.40,-2.30,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
5,2019-06-25 13:21:14.500,0.0,574.0,0.0,0.00,-0.01,0.0,391.40,-2.30,21.0,...,0.4,1,0,0,25.5,0,0,0,30.50,24.5
6,2019-06-25 13:21:14.600,0.0,574.0,0.0,0.00,-0.01,0.0,391.40,-2.30,21.0,...,0.4,1,0,0,25.5,0,0,0,30.45,24.5
7,2019-06-25 13:21:14.700,0.0,574.0,0.0,0.00,-0.03,0.0,391.40,-2.31,21.0,...,0.4,1,0,0,25.5,0,0,0,30.40,24.5
8,2019-06-25 13:21:14.800,0.0,574.0,0.0,0.38,-0.01,0.0,391.40,-2.36,21.0,...,0.4,1,0,0,25.5,0,0,0,30.35,24.5
9,2019-06-25 13:21:14.900,0.0,574.0,0.0,0.12,-0.01,0.0,391.40,-2.37,21.0,...,0.4,1,0,0,25.5,0,0,0,30.30,24.5
10,2019-06-25 13:21:15.000,0.0,574.0,0.0,0.38,0.01,0.0,391.40,-2.27,21.0,...,0.4,1,0,0,25.5,0,0,0,30.25,24.5
11,2019-06-25 13:21:15.100,0.0,574.0,0.0,0.00,-0.02,0.0,391.40,-2.21,21.0,...,0.4,1,0,0,25.5,0,0,0,30.20,24.5
12,2019-06-25 13:21:15.200,0.0,574.0,0.0,0.00,-0.03,0.0,391.40,-2.26,21.0,...,0.4,1,0,0,25.5,0,0,0,30.15,24.5
13,2019-06-25 13:21:15.300,0.0,574.0,0.0,0.00,-0.01,0.0,391.40,-2.33,21.0,...,0.4,1,0,0,25.5,0,0,0,30.10,24.5
14,2019-06-25 13:21:15.400,0.0,574.0,0.0,0.00,0.02,0.0,391.40,-2.43,21.0,...,0.4,1,0,0,25.5,0,0,0,30.05,24.5
15,2019-06-25 13:21:15.500,0.0,574.0,0.0,0.00,0.00,0.0,391.39,-2.54,21.0,...,0.4,1,0,0,25.5,0,0,0,30.00,24.5
16,2019-06-25 13:21:15.600,0.0,574.0,0.0,0.00,-0.03,0.0,391.34,-2.69,21.0,...,0.4,1,0,0,25.5,0,0,0,30.00,24.5
17,2019-06-25 13:21:15.700,0.0,574.0,0.0,0.00,-0.01,0.0,391.30,-2.83,21.0,...,0.4,1,0,0,25.5,0,0,0,30.00,24.5
18,2019-06-25 13:21:15.800,0.0,574.0,0.0,0.23,-0.03,0.0,391.30,-2.93,21.0,...,0.4,1,0,0,25.5,0,0,0,30.00,24.5
19,2019-06-25 13:21:15.900,0.0,574.0,0.0,0.23,-0.03,0.0,391.30,-3.03,21.0,...,0.4,1,0,0,25.5,0,0,0,30.00,24.5

In [ ]:
import pandas as pd
import datetime

# 시간 데이터를 datetime 객체로 변환합니다.
dfA['Time [s]'] = pd.to_datetime(dfA['Time [s]'], format='%Y-%m-%d_%H-%M-%S')

# 0.1초 단위로 시간을 증가시킵니다.
new_time_list = []
for i in range(len(dfA)):
    if i % 10 == 0 and i != 0:  # 10번째 인덱스마다
        new_time_list[-10:] = [new_time_list[-10] + datetime.timedelta(seconds=0.1*j) for j in range(10)]
    new_time_list.append(dfA['Time [s]'][i])

dfA['Time [s]'] = new_time_list

In [ ]:
dfB = pd.read_csv('/content/drive/MyDrive/23년도 2학기 학술제/TripA01.csv',encoding='CP949', delimiter=';')

In [ ]:
dfA = pd.read_csv('/content/drive/MyDrive/23년도 2학기 학술제/TripA01.csv',encoding='CP949', delimiter=';')
start_time_str = '2019-06-25_13-21-14'
start_time = datetime.strptime(start_time_str, '%Y-%m-%d_%H-%M-%S')

time_values = dfA['Time [s]']

new_time_values = [(start_time + timedelta(seconds=time)).strftime('%Y-%m-%d_%H-%M-%S') for time in time_values]

dfA['Time [s]'] = new_time_values

## 한번에 다 합치는 코드

In [ ]:
import os
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd

folder_path = '/content/drive/MyDrive/MeasurementData'

file_list = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if 'Trip' in file and file.endswith('.csv')]

for file in file_list:
  try:
    df = pd.read_csv(file, encoding='utf-8', sep=';')
  except UnicodeDecodeError:
    df = pd.read_csv(file, encoding='ISO-8859-1', sep=';')

  file_name = os.path.splitext(os.path.basename(file))[0]

  df['Original_File_Name'] = file_name

  parquet_file = file.replace('.csv', '.parquet')

  table = pa.Table.from_pandas(df)
  pq.write_table(table, parquet_file)

In [ ]:
import os
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd

folder_path = '/content/drive/MyDrive/MeasurementData'

file_list = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if 'Trip' in file and file.endswith('.csv')]

for file in file_list:
  try:
    df = pd.read_csv(file, encoding='utf-8', sep=';')
  except UnicodeDecodeError:
    df = pd.read_csv(file, encoding='ISO-8859-1', sep=';')

  file_name = os.path.splitext(os.path.basename(file))[0]

  df['Original_File_Name'] = file_name

  parquet_file = file.replace('.csv', '.parquet')

  table = pa.Table.from_pandas(df)
  pq.write_table(table, parquet_file)

In [ ]:
parquet_files = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if file.endswith('.parquet')]

first_file = pq.read_table(parquet_files[0])
all_data = first_file.to_pandas()

for file in parquet_files[1:]:
  table = pq.read_table(file)
  df = table.to_pandas()
  all_data = all_data.append(df, ignore_index=False)

In [ ]:
all_data

,Time [s],Velocity [km/h],Elevation [m],Throttle [%],Motor Torque [Nm],Longitudinal Acceleration [m/s^2],Regenerative Braking Signal,Battery Voltage [V],Battery Current [A],Battery Temperature [°C],...,Temperature Footweel Co-Driver [°C],Temperature Feetvent Co-Driver [°C],Temperature Feetvent Driver [°C],Temperature Head Co-Driver [°C],Temperature Head Driver [°C],Temperature Vent right [°C],Temperature Vent central right [°C],Temperature Vent central left [°C],Temperature Vent right [°C],Velocity [km/h]]]
0,0.0,0.0,582.0,0.0,0.0,0.19,0.0,386.8,-1.70,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.1,0.0,582.0,0.0,0.0,0.20,0.0,386.8,-1.70,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.2,0.0,582.0,0.0,0.0,0.24,0.0,386.8,-1.70,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.3,0.0,582.0,0.0,0.0,0.25,0.0,386.8,-1.70,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.4,0.0,582.0,0.0,0.0,0.22,0.0,386.8,-1.74,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56097,5609.7,0.0,654.0,0.0,0.0,-0.21,0.0,389.2,92.90,14.0,...,24.49,36.27,33.70,21.7,22.42,32.26,32.34,32.61,30.86,NaN
56098,5609.8,0.0,654.0,0.0,0.0,-0.21,0.0,389.2,92.90,14.0,...,24.49,36.27,33.46,21.7,22.41,32.26,32.34,32.61,30.86,NaN
56099,5609.9,0.0,654.0,0.0,0.0,-0.21,0.0,389.2,92.90,14.0,...,24.49,36.27,33.23,21.7,22.40,32.26,32.34,32.61,30.86,NaN
56100,5610.0,0.0,654.0,0.0,0.0,-0.21,0.0,389.2,92.90,14.0,...,24.49,36.27,32.99,21.7,22.40,32.26,32.34,32.61,30.86,NaN
56101,5610.1,0.0,654.0,0.0,0.0,-0.21,0.0,389.2,92.90,14.0,...,24.49,36.27,32.95,21.7,22.39,32.26,32.34,32.61,30.86,NaN

In [ ]:
all_data.columns

Index(['Time [s]', 'Velocity [km/h]', 'Elevation [m]', 'Throttle [%]',
       'Motor Torque [Nm]', 'Longitudinal Acceleration [m/s^2]',
       'Regenerative Braking Signal ', 'Battery Voltage [V]',
       'Battery Current [A]', 'Battery Temperature [°C]',
       'max. Battery Temperature [°C]', 'SoC [%]', 'displayed SoC [%]',
       'min. SoC [%]', 'max. SoC [%)', 'Heating Power CAN [kW]',
       'Requested Heating Power [W]', 'AirCon Power [kW]', 'Heater Signal',
       'Ambient Temperature [°C]', 'Requested Coolant Temperature [°C]',
       'Heat Exchanger Temperature [°C]', 'Cabin Temperature Sensor [°C]',
       'Original_File_Name', 'Heating Power LIN [W]', 'Heater Voltage [V]',
       'Heater Current [A]', 'Coolant Temperature Heatercore [°C]',
       'Coolant Temperature Inlet [°C]', 'Unnamed: 23',
       'Ambient Temperature Sensor [°C]', 'Coolant Volume Flow +500 [l/h]',
       'Temperature Coolant Heater Inlet [°C]',
       'Temperature Coolant Heater Outlet [°C]',
       'Temperature Heat Exchanger Outlet [°C]',
       'Temperature Defrost lateral left [°C]',
       'Temperature Defrost lateral right [°C]',
       'Temperature Defrost central [°C]',
       'Temperature Defrost central left [°C]',
       'Temperature Defrost central right [°C]',
       'Temperature Footweel Driver [°C]',
       'Temperature Footweel Co-Driver [°C]',
       'Temperature Feetvent Co-Driver [°C]',
       'Temperature Feetvent Driver [°C]', 'Temperature Head Co-Driver [°C]',
       'Temperature Head Driver [°C]', 'Temperature Vent right [°C] ',
       'Temperature Vent central right [°C]',
       'Temperature Vent central left [°C]', 'Temperature Vent right [°C]',
       'Velocity [km/h]]]'],
      dtype='object')

In [ ]:
all_data['Unnamed: 23']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
56097   NaN
56098   NaN
56099   NaN
56100   NaN
56101   NaN
Name: Unnamed: 23, Length: 1094793, dtype: float64

Cabin Temperature Sensor 결측치를 채우기 위해 Cabin Temperature Sensor와 연관있는 변수 찾기

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/23년도 2학기 학술제/11-29_tripA변수삭제/TripA26.csv')
correlation = df.corr()
plt.figure(figsize=(20, 20))  # 히트맵의 크기를 설정합니다.
sns.heatmap(correlation, annot=True, cmap='coolwarm')  # 히트맵을 그립니다.
plt.show()  # 그래프를 화면에 출력합니다.

# 여기서부터 최종 전처리실행

# TripA 전처리 마무리

In [ ]:
import pandas as pd

# 데이터셋 이름이 저장되어 있는 리스트
dataset_names = [f'TripA{i:02d}' for i in range(1, 33)]

# 빈 리스트를 생성합니다. 이곳에 각 데이터셋을 불러와 저장할 것입니다.
datasets = []

# Overview 데이터셋 불러오기
overview = pd.read_excel('/content/drive/MyDrive/23년도 2학기 학술제/11-29/Overview 수정.xlsx')

for col in overview.columns:
        new_col = col.split(' [')[0]  # ' [' 문자를 기준으로 문자열을 분리하고, 그 중 첫 번째 부분을 선택합니다.
        overview.rename(columns={col: new_col}, inplace=True)

for i, dataset_name in enumerate(dataset_names, start=1):
    # 데이터셋 불러오기
    df = pd.read_csv(f'/content/drive/MyDrive/23년도 2학기 학술제/11-29_변수처리/{dataset_name}.csv', encoding='cp949')

    # 'TripID' 열 추가
    df['TripID'] = i

    # Overview 데이터와 병합
    trip_info = overview[overview['Trip'] == dataset_name]  # 해당하는 Trip의 정보를 가져옵니다.
    for column in trip_info.columns:
        df[column] = trip_info[column].values[0]  # 가져온 정보를 df에 추가합니다.

    # 불러온 데이터셋을 리스트에 추가
    datasets.append(df)

# 모든 데이터셋을 하나로 합치기
total_data = pd.concat(datasets, ignore_index=True)

In [ ]:
total_data.columns

Index(['Time', 'Velocity', 'Elevation', 'Throttle', 'Motor Torque',
       'Longitudinal Acceleration', 'Regenerative Braking Signal ',
       'Battery Voltage', 'Battery Current', 'Battery Temperature',
       'max. Battery Temperature', 'SoC', 'displayed SoC', 'min. SoC',
       'max. SoC', 'Heating Power CAN', 'Requested Heating Power',
       'AirCon Power', 'Heater Signal', 'Ambient Temperature',
       'Requested Coolant Temperature', 'Heat Exchanger Temperature',
       'Cabin Temperature Sensor', 'TripID', 'Trip', 'Date', 'Route/Area',
       'Weather', 'Battery Temperature (Start)', 'Battery Temperature (End)',
       'Battery State of Charge (Start)', 'Battery State of Charge (End)',
       'Using Battery State of Charge', 'Ambient Temperature (Start)',
       'Target Cabin Temperature', 'Distance', 'Duration', 'Fan', 'Note'],
      dtype='object')

In [ ]:
import pandas as pd


# 속도를 m/s로 변환 (km/h를 m/s로 변환하려면 5/18을 곱해야 함)
total_data['Velocity [m/s]'] = total_data['Velocity']*5/18

# 각 시간 단위 동안의 이동 거리 계산 (속도*시간)
total_data['Distance [m]'] = total_data['Velocity [m/s]']*0.1

# 'Cumulative Distance [m]'는 실시간 주행 누적 거리

# 각 주행마다 누적 거리를 계산하기 위해 groupby를 사용
total_data['Cumulative Distance [m]'] = total_data.groupby('TripID')['Distance [m]'].cumsum()

# 'Cumulative Distance [m]' 열을 km 단위로 변환
total_data['Cumulative Distance [km]'] = total_data['Cumulative Distance [m]'] / 1000

In [ ]:
total_data['remaining_distance']

0         127.734167
1         127.734167
2         127.734167
3         127.734167
4         127.734167
             ...
467696     80.797720
467697     80.797720
467698     80.797720
467699     80.797720
467700     80.797720
Name: remaining_distance, Length: 467701, dtype: float64

In [ ]:
total_data['use_power'] = 18.8 * abs(total_data['SoC'].iloc[0] - total_data['SoC']) / 100

# 이동거리 당 에너지 소비 계산
total_data['energy_per_distance'] = total_data['use_power'] / total_data['Cumulative Distance [km]']


total_data['energy_per_distance'].fillna(0, inplace=True)
# 'energy_per_distance' 값이 0인 경우 대체값 사용

total_data['energy_per_distance'] = total_data['energy_per_distance'].replace(0, 0.1279)

# 남은 주행 가능 거리 계산
total_data['remaining_distance'] = (18.8 * (total_data['SoC']/100)) / total_data['energy_per_distance']

In [ ]:
print(total_data.isnull().any())

Time                               False
Velocity                           False
Elevation                          False
Throttle                           False
Motor Torque                       False
Longitudinal Acceleration          False
Regenerative Braking Signal        False
Battery Voltage                    False
Battery Current                    False
Battery Temperature                False
max. Battery Temperature           False
SoC                                False
displayed SoC                      False
min. SoC                           False
max. SoC                           False
Heating Power CAN                  False
Requested Heating Power            False
AirCon Power                       False
Heater Signal                      False
Ambient Temperature                False
Requested Coolant Temperature      False
Heat Exchanger Temperature         False
Cabin Temperature Sensor           False
TripID                             False
Trip                               False
Date                               False
Route/Area                         False
Weather                            False
Battery Temperature (Start)        False
Battery Temperature (End)          False
Battery State of Charge (Start)    False
Battery State of Charge (End)      False
Using Battery State of Charge      False
Ambient Temperature (Start)        False
Target Cabin Temperature           False
Distance                           False
Duration                           False
Fan                                False
Note                                True
Velocity [m/s]                     False
Distance [m]                       False
Cumulative Distance [m]            False
Cumulative Distance [km]           False
use_power                          False
energy_per_distance                False
remaining_distance                 False
dtype: bool

In [ ]:
total_data['Note'] = total_data['Note'].fillna('No')
total_data['Battery Power'] = total_data['Battery Voltage'] * total_data['Battery Current']
total_data = total_data.drop(['Trip', 'Fan', 'Date', 'Battery State of Charge (Start)', 'Battery State of Charge (End)','Battery Voltage', 'Battery Current',
                              'Velocity [m/s]', 'Distance [m]', 'Cumulative Distance [m]', 'Cumulative Distance [km]', 'use_power', 'energy_per_distance', 'remaining_distance'], axis=1)

columns_to_multiply = ['Using Battery State of Charge']
for column in columns_to_multiply:
    total_data[column] = total_data[column] * 100

In [ ]:
total_data['Weather'] = total_data['Weather'].replace({'slightly cloudy': 'cloudy'})

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np


encoder = LabelEncoder()
encoder.classes_ = np.array(['rainy', 'cloudy', 'sunny'])

total_data['Weather'] = encoder.transform(total_data['Weather'])

# 인코딩된 라벨과 원래의 라벨 매핑
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'rainy', 1: 'cloudy', 2: 'sunny'}

In [ ]:
from sklearn.preprocessing import LabelEncoder

# 라벨 인코더 생성
encoder = LabelEncoder()

# 라벨 인코딩 수행
total_data['Route/Area'] = encoder.fit_transform(total_data['Route/Area'])

# 인코딩된 라벨과 원래의 라벨 매핑
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'Munich East', 1: 'Munich North'}

In [ ]:
from sklearn.preprocessing import LabelEncoder

# 라벨 인코더 생성
encoder = LabelEncoder()

# 라벨 인코딩 수행
total_data['Note'] = encoder.fit_transform(total_data['Note'])

# 인코딩된 라벨과 원래의 라벨 매핑
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'No', 1: 'Target Cabin Temperature changed '}

# TripB 전처리 마무리

In [ ]:
import pandas as pd

# 데이터셋 이름이 저장되어 있는 리스트
dataset_names = [f'TripB{i:02d}' for i in range(1, 39)]

# 빈 리스트를 생성합니다. 이곳에 각 데이터셋을 불러와 저장할 것입니다.
datasets = []

# Overview 데이터셋 불러오기
overview = pd.read_excel('/content/drive/MyDrive/23년도 2학기 학술제/11-29/Overview 수정.xlsx')

for col in overview.columns:
        new_col = col.split(' [')[0]  # ' [' 문자를 기준으로 문자열을 분리하고, 그 중 첫 번째 부분을 선택합니다.
        overview.rename(columns={col: new_col}, inplace=True)

for i, dataset_name in enumerate(dataset_names, start=1):
    # 데이터셋 불러오기
    df = pd.read_csv(f'/content/drive/MyDrive/23년도 2학기 학술제/11-29_변수처리/{dataset_name}.csv', encoding='cp949')

    # 'TripID' 열 추가
    df['TripID'] = i

    # Overview 데이터와 병합
    trip_info = overview[overview['Trip'] == dataset_name]  # 해당하는 Trip의 정보를 가져옵니다.
    for column in trip_info.columns:
        df[column] = trip_info[column].values[0]  # 가져온 정보를 df에 추가합니다.

    # 불러온 데이터셋을 리스트에 추가
    datasets.append(df)

# 모든 데이터셋을 하나로 합치기
total_dataB = pd.concat(datasets, ignore_index=True)

In [ ]:
total_dataB.columns

Index(['Time', 'Velocity', 'Elevation', 'Throttle', 'Motor Torque',
       'Longitudinal Acceleration', 'Regenerative Braking Signal ',
       'Battery Voltage', 'Battery Current', 'Battery Temperature',
       'max. Battery Temperature', 'SoC', 'displayed SoC', 'min. SoC',
       'max. SoC', 'Heating Power CAN', 'Requested Heating Power',
       'AirCon Power', 'Heater Signal', 'Ambient Temperature',
       'Ambient Temperature Sensor', 'Requested Coolant Temperature',
       'Coolant Volume Flow +500', 'Heat Exchanger Temperature',
       'Cabin Temperature Sensor', 'Temperature Coolant Heater Inlet',
       'Temperature Coolant Heater Outlet',
       'Temperature Heat Exchanger Outlet', 'Temperature Defrost lateral left',
       'Temperature Defrost lateral right', 'Temperature Defrost central',
       'Temperature Defrost central left', 'Temperature Defrost central right',
       'Temperature Footweel Driver', 'Temperature Footweel Co-Driver',
       'Temperature Feetvent Co-Driver', 'Temperature Feetvent Driver',
       'Temperature Head Co-Driver', 'Temperature Head Driver',
       'Temperature Vent right', 'Temperature Vent central right',
       'Temperature Vent central left', 'Temperature Vent right.1', 'TripID',
       'Trip', 'Date', 'Route/Area', 'Weather', 'Battery Temperature (Start)',
       'Battery Temperature (End)', 'Battery State of Charge (Start)',
       'Battery State of Charge (End)', 'Using Battery State of Charge',
       'Ambient Temperature (Start)', 'Target Cabin Temperature', 'Distance',
       'Duration', 'Fan', 'Note'],
      dtype='object')

In [ ]:
print(total_dataB.isnull().any())

In [ ]:
total_dataB['Note'] = total_dataB['Note'].fillna('No')
total_dataB['Battery Power'] = total_dataB['Battery Voltage'] * total_dataB['Battery Current']
total_dataB = total_dataB.drop(['Trip', 'Fan', 'Date', 'Battery State of Charge (Start)', 'Battery State of Charge (End)','Battery Voltage', 'Battery Current' ], axis=1)

columns_to_multiply = ['Using Battery State of Charge']

for column in columns_to_multiply:
    total_dataB[column] = total_dataB[column] * 100

In [ ]:
total_dataB['Weather'] = total_dataB['Weather'].replace({'slightly cloudy': 'cloudy', 'dark, little rainy': 'rain', 'sunset':'sunrise'})

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.classes_ = np.array(['rain', 'cloudy', 'sunny', 'dark', 'sunrise'])

total_dataB['Weather'] = encoder.transform(total_dataB['Weather'])
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'rain', 1: 'cloudy', 2: 'sunny', 3: 'dark', 4: 'sunrise'}

In [ ]:
total_dataB['Route/Area'] = total_dataB['Route/Area'].replace({'FTMRoute (2x)': 'FTMRoute', 'Munich North + Fast Charging': 'Munich North', 'FTMRoute reverse':'FTMRoute'})

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.classes_ = np.array(['Munich East', 'Munich North', 'Munich Northeast', 'Munich South', 'Highway','FTMRoute'])

total_dataB['Route/Area'] = encoder.transform(total_dataB['Route/Area'])
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'Munich East', 1: 'Munich North', 2: 'Munich Northeast', 3: 'Munich South', 4: 'Highway', 5: 'FTMRoute'}

In [ ]:
print(total_dataB['Note'].unique())

['No' 'Sunday -> little traffic' 'Rush Hour' "Fast Charging, '+70 kg"
 '+70 kg' '+70kg' 'FTMRoute' 'FTMRoute (directly after previous trip)'
 'FTM Route (directly after previous trip)' '+80 kg' '+60 kg ' '+70 kg '
 'Sunday -> little traffic, (directly after previous trip)' '+ 160 kg'
 'Open door at 37:10 and 42:00 for 30s']

In [ ]:
total_dataB['Note'] = total_dataB['Note'].replace({'Sunday -> little traffic': 'little traffic',
                                                   'Sunday -> little traffic, (directly after previous trip)': 'little traffic',
                                                   'Open door at 37:10 and 42:00 for 30s':'No',
                                                   'FTMRoute (directly after previous trip)':'No',
                                                   'FTM Route (directly after previous trip)':'No',
                                                   'FTMRoute':'No',
                                                   "Fast Charging, '+70 kg":'+70 kg',
                                                   '+70kg':'+70 kg',
                                                   '+70 kg ':'+70 kg',
                                                   '+80 kg':'+70 kg',
                                                   '+60 kg ':'+70 kg'})

In [ ]:
encoder = LabelEncoder()
encoder.classes_ = np.array(['No', 'little traffic', '+70 kg', '+ 160 kg', 'Rush Hour'])
total_dataB['Note'] = encoder.transform(total_dataB['Note'])

# 인코딩된 라벨과 원래의 라벨 매핑
label_mapping = {index: label for index, label in enumerate(encoder.classes_)}

print(label_mapping)

{0: 'No', 1: 'little traffic', 2: '+70 kg', 3: '+ 160 kg', 4: 'Rush Hour'}

## light GBM 모델 생성

In [ ]:
 pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm) (1.11.3)

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

total_data

,Time,Velocity,Elevation,Throttle,Motor Torque,Longitudinal Acceleration,Regenerative Braking Signal,Battery Temperature,max. Battery Temperature,SoC,...,Weather,Battery Temperature (Start),Battery Temperature (End),Using Battery State of Charge,Ambient Temperature (Start),Target Cabin Temperature,Distance,Duration,Note,Battery Power
0,0.0,0.0,574.0,0.0,0.0,-0.03,0.0,21.0,22.0,86.9,...,2,21,22,6.0,25.5,23.0,7.42769,16.820000,0,-861.080
1,0.1,0.0,574.0,0.0,0.0,0.00,0.0,21.0,22.0,86.9,...,2,21,22,6.0,25.5,23.0,7.42769,16.820000,0,-864.994
2,0.2,0.0,574.0,0.0,0.0,-0.01,0.0,21.0,22.0,86.9,...,2,21,22,6.0,25.5,23.0,7.42769,16.820000,0,-884.564
3,0.3,0.0,574.0,0.0,0.0,-0.03,0.0,21.0,22.0,86.9,...,2,21,22,6.0,25.5,23.0,7.42769,16.820000,0,-900.220
4,0.4,0.0,574.0,0.0,0.0,-0.03,0.0,21.0,22.0,86.9,...,2,21,22,6.0,25.5,23.0,7.42769,16.820000,0,-900.220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467696,1671.7,0.0,597.0,0.0,0.0,0.61,0.0,26.0,27.0,59.5,...,1,21,26,27.0,20.0,27.5,37.20769,27.868333,0,-918.416
467697,1671.8,0.0,597.0,0.0,0.0,0.60,0.0,26.0,27.0,59.5,...,1,21,26,27.0,20.0,27.5,37.20769,27.868333,0,-907.124
467698,1671.9,0.0,597.0,0.0,0.0,0.60,0.0,26.0,27.0,59.5,...,1,21,26,27.0,20.0,27.5,37.20769,27.868333,0,-925.944
467699,1672.0,0.0,597.0,0.0,0.0,0.58,0.0,26.0,27.0,59.5,...,1,21,26,27.0,20.0,27.5,37.20769,27.868333,0,-937.236
467700,1672.1,0.0,597.0,0.0,0.0,0.56,0.0,26.0,27.0,59.5,...,1,21,26,27.0,20.0,27.5,37.20769,27.868333,0,-918.416

In [ ]:
total_data['Battery Power'].sum()

-2696555889.85486

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

# 붓꽃 데이터 세트를 로딩한다.
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있다.
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있다.
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환한다.
iris_df = pd.DataFrame(data =  iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [ ]:
# coding: utf-8
import pandas as pd
from sklearn.metrics import mean_squared_error
import lightgbm as lgb

lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval = lgb.Dataset(X_test, y_test, reference=lgb_train)
# specify your configurations as a dict
params = {
    'boosting_type': 'gbdt',
    'metric': {'l2', 'l1'},
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

callbacks = [lgb.callback.early_stopping(5)]

print('Starting training...')

# train
gbm = lgb.train(params,
                lgb_train,
                num_boost_round=20,
                valid_sets=[lgb_eval],
                callbacks=callbacks)

print('Saving model...')

# save model to file
gbm.save_model('model.txt')

print('Starting predicting...')
# predict
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)
# eval
print('The rmse of prediction is:', mean_squared_error(y_test, y_pred) ** 0.5)

Starting training...
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 5 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Did not meet early stopping. Best iteration is:
[20]	valid_0's l1: 0.312196	valid_0's l2: 0.156372
Saving model...
Starting predicting...
The rmse of prediction is: 0.3954394042475458